spring:
  profiles:
    active: dev
#  rabbitmq:
#    host: 47.106.183.36
#    port: 5672
#    username: guest
#    password: guest
#    publisher-confirm-type: correlated
#    publisher-returns: true
#  mqtt:
#    username: admin                            # 账号
#    password: admin                      # 密码
#    host-url: tcp://47.106.183.36:1883                    # mqtt连接tcp地址
#    client-id: test                            # 客户端Id，每个启动的id要不同
#    default-topic: test                        # 默认主题
#    timeout: 100                            # 超时时间
#    keepalive: 100                            # 保持连接数
      # 文件上传
  servlet:
    multipart:
          # 单个文件大小
      max-file-size: 100MB
          # 设置总上传的文件大小
      max-request-size: 200MB
  mail:
    password: tmrcynpkheucccjg
    username: 1781088254@qq.com
    port: 587
    host: smtp.qq.com
    default-encoding: UTF-8
minio:
#  endpoint: http://47.106.183.36:9000 #MinIO服务所在地址
  endpoint: http://kin.qinsy.ltd:9080 #MinIO服务所在地址
  bucketName: taskmanagement #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
server:
  port: 8081
---
# DataSource Config
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://kin.qinsy.ltd:3306/taskmanagement?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: taskmanagement
    password: znjz202
  redis:
    database: 0
    host: kin.qinsy.ltd      # Redis服务器地址
    port: 6379              # Redis服务器连接端口
    password: 123456               # Redis服务器连接密码（默认为空）
    pool:
      max-active: 200       # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 10          # 连接池中的最大空闲连接
      max-wait: -1          # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 0           # 连接池中的最小空闲连接
#  security:
#    user:
#      name: user
#      password: 111111
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
sjj:
  jwt:
    header: Authorization
    expire: 604800 #7天
    secret: ji8n3439n439n43ld9ne9343fdfer49h
---
spring:
  profiles: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.33.180:3306/testdb?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: testdb
    password: 123456
  redis:
    database: 0
    host: 47.93.33.180         # Redis服务器地址
    port: 6379              # Redis服务器连接端口
    password:               # Redis服务器连接密码（默认为空）
    pool:
      max-active: 200       # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 10          # 连接池中的最大空闲连接
      max-wait: -1          # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 0           # 连接池中的最小空闲连接
#  security:
#    user:
#      name: user
#      password: 111111
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
sjj:
  jwt:
    header: Authorization
    expire: 604800 #7天
    secret: ji8n3439n439n43ld9ne9343fdfer49h